name: ssr_flutter_and_nestjs
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: write 
jobs:
  test_nestjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm run test
      
      - name: Build NestJS project
        run: npm run build
      
      - name: Deploy NestJS
        run: node dist/main


  test_flutter:
    needs: test_nestjs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Analyze project source
        run: flutter analyze
      
      - name: Run tests
        run: flutter test --coverage
      
  build_and_deploy_flutter:
    needs: test_flutter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SSR_FLUTTER }}  
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
          channel: 'stable'
      
      - name: Enable web
        run: flutter config --enable-web
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build web
        run: flutter build web --release --output ./public/ssr_flutter --base-href /ssr-flutter/
      
      - name: Deploy Flutter web
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SSR_FLUTTER }}
          publish_dir: ./public/ssr_flutter
          force_orphan: true